apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wh72aogw5-nodejs
  janus-idp.io/tekton: wh72aogw5-nodejs
  backstage.io/kubernetes-id: wh72aogw5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wh72aogw5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
