apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wh72aogw5-nodejs 
  janus-idp.io/tekton: wh72aogw5-nodejs
  backstage.io/kubernetes-id: wh72aogw5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wh72aogw5-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml